#### 1.Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included). The numbers obtained should be printed in a comma-separated sequence on a single line. ##

In [1]:

for i in range(2000,3201):
    if (i%2 == 0) and (i%5!=0):
        print(i, end=",")

2002,2004,2006,2008,2012,2014,2016,2018,2022,2024,2026,2028,2032,2034,2036,2038,2042,2044,2046,2048,2052,2054,2056,2058,2062,2064,2066,2068,2072,2074,2076,2078,2082,2084,2086,2088,2092,2094,2096,2098,2102,2104,2106,2108,2112,2114,2116,2118,2122,2124,2126,2128,2132,2134,2136,2138,2142,2144,2146,2148,2152,2154,2156,2158,2162,2164,2166,2168,2172,2174,2176,2178,2182,2184,2186,2188,2192,2194,2196,2198,2202,2204,2206,2208,2212,2214,2216,2218,2222,2224,2226,2228,2232,2234,2236,2238,2242,2244,2246,2248,2252,2254,2256,2258,2262,2264,2266,2268,2272,2274,2276,2278,2282,2284,2286,2288,2292,2294,2296,2298,2302,2304,2306,2308,2312,2314,2316,2318,2322,2324,2326,2328,2332,2334,2336,2338,2342,2344,2346,2348,2352,2354,2356,2358,2362,2364,2366,2368,2372,2374,2376,2378,2382,2384,2386,2388,2392,2394,2396,2398,2402,2404,2406,2408,2412,2414,2416,2418,2422,2424,2426,2428,2432,2434,2436,2438,2442,2444,2446,2448,2452,2454,2456,2458,2462,2464,2466,2468,2472,2474,2476,2478,2482,2484,2486,2488,2492,2494,2496,2498,2502,2504,2506,2508,2512,2514,2516,2518,2522,2524,2526,2528,2532,2534,2536,2538,2542,2544,2546,2548,2552,2554,2556,2558,2562,2564,2566,2568,2572,2574,2576,2578,2582,2584,2586,2588,2592,2594,2596,2598,2602,2604,2606,2608,2612,2614,2616,2618,2622,2624,2626,2628,2632,2634,2636,2638,2642,2644,2646,2648,2652,2654,2656,2658,2662,2664,2666,2668,2672,2674,2676,2678,2682,2684,2686,2688,2692,2694,2696,2698,2702,2704,2706,2708,2712,2714,2716,2718,2722,2724,2726,2728,2732,2734,2736,2738,2742,2744,2746,2748,2752,2754,2756,2758,2762,2764,2766,2768,2772,2774,2776,2778,2782,2784,2786,2788,2792,2794,2796,2798,2802,2804,2806,2808,2812,2814,2816,2818,2822,2824,2826,2828,2832,2834,2836,2838,2842,2844,2846,2848,2852,2854,2856,2858,2862,2864,2866,2868,2872,2874,2876,2878,2882,2884,2886,2888,2892,2894,2896,2898,2902,2904,2906,2908,2912,2914,2916,2918,2922,2924,2926,2928,2932,2934,2936,2938,2942,2944,2946,2948,2952,2954,2956,2958,2962,2964,2966,2968,2972,2974,2976,2978,2982,2984,2986,2988,2992,2994,2996,2998,3002,3004,3006,3008,3012,3014,3016,3018,3022,3024,3026,3028,3032,3034,3036,3038,3042,3044,3046,3048,3052,3054,3056,3058,3062,3064,3066,3068,3072,3074,3076,3078,3082,3084,3086,3088,3092,3094,3096,3098,3102,3104,3106,3108,3112,3114,3116,3118,3122,3124,3126,3128,3132,3134,3136,3138,3142,3144,3146,3148,3152,3154,3156,3158,3162,3164,3166,3168,3172,3174,3176,3178,3182,3184,3186,3188,3192,3194,3196,3198,

#### 2.Write a Python program to accept the user's first and last name and then getting them printed in the the reverse order with a space between first name and last name.

In [2]:
firstName = input("Enter your First name")
lastName = input("enter your last name")
rev1 = firstName[::-1]
rev2 = lastName[::-1]
print(rev1,end=" ")
print(rev2)

Enter your First nameArjun
enter your last nameKhamkar
nujrA rakmahK

#### 3.Write a Python program to find the volume of a sphere with diameter 12 cm.

#### Formula: V=4/3 * Ï€ * r 3

In [6]:
V = 4/3 * 3.14 * 12**2
print(V)

602.88